# FAKE SECRETS FOR GITLEAKS TESTING

AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

GITHUB_TOKEN = "ghp_1234567890abcdefghijklmnopqrstuvwxyz"

DB_PASSWORD = "SuperSecretPassword123!"
