name: PayliteNG DevSecOps Security Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  bandit-sast:
    name: Bandit SAST Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit
      run: |
        bandit -r app \
        --severity-level high || true


  dependency-scan:
    name: pip-audit Dependency Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install pip-audit
      run: pip install pip-audit

    - name: Run pip-audit
      run: |
        pip-audit -r requirements.txt


  secret-detection:
    name: Gitleaks Secret Detection
    runs-on: ubuntu-latest

    steps:
    - name: Checkout full history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
